default: Murnaghan

Murnaghan: Fe.in
	../murnaghan.sh Fe 2.65 2.85 0.05 bcc Fe-BCC-LDA.dat
clean:
	rm -rf *.out *DM *.png CH* fe.* ORB* KB* out* siesta.* VNA* \
            RE* CLOCK *xml *ion *.FA *CG *EIG *KP *POT.CONF *alloc \
            *~ *.STRUCT_OUT  INPUT* tmp
clean_dat:
	rm -rf *.dat
