default: Murnaghan

Murnaghan: Fe.in
	../murnaghan.sh Fe 3.35 3.65 0.05 fcc Fe-FCC-GGA.dat
clean:
	rm -rf *.out *DM *.png CH* fe.* ORB* KB* out* siesta.* VNA* \
            RE* CLOCK *xml *ion *.FA *CG *EIG *KP *POT.CONF *alloc \
            *~ *.STRUCT_OUT  INPUT* tmp
clean_dat:
	rm -rf *.dat
