default: Murnaghan

Murnaghan: Fe.in
	../murnaghan.sh Fe 3.30 3.55 0.05 fcc Fe-FCC-LDA.dat
clean:
	rm -rf *.out *DM *.png CH* fe.* ORB* KB* out* siesta.* VNA* \
            RE* CLOCK *xml *ion *.FA *CG *EIG *KP *POT.CONF *alloc \
            *~ *.STRUCT_OUT tmp
clean_dat:
	rm -rf *.dat
